[package]
name = "prost-types"
version = "0.11.8"
authors = [
    "Dan Burkert <dan@danburkert.com>",
    "Lucio Franco <luciofranco14@gmail.com",
    "Tokio Contributors <team@tokio.rs>",
]
license = "Apache-2.0"
repository = "https://github.com/tokio-rs/prost"
documentation = "https://docs.rs/prost-types"
readme = "README.md"
description = "A Protocol Buffers implementation for the Rust Language."
edition = "2021"
rust-version = "1.60"

[lib]
doctest = false

[features]
default = ["std"]
std = ["prost/std"]
json = ["prost/json", "serde"]

[dependencies]
prost = { version = "0.11.8", path = "..", default-features = false, features = ["prost-derive"] }
base64 = "0.13"
bytes = { version = "1", default-features = false }
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
proptest = "1"
serde_json = "1"
